name: MagiUtils
version: 1.0
author: HeyZeer0
main: net.heyzeer0.magi.Main
commands:
  magireload:
     description: Faça reaload na config do plugin.
  chunkdebug:
     description: Faça um chunk debug.